import { supabase } from "./supabase";

// Download a real PDF statement generated by the `statements` Edge Function from
// the signed-in user's own server data. Fetches the PDF as a blob and triggers a
// browser download.
//
// type "expenses" = customer (what they paid); "earnings" = agent (what they earned).

const SB_URL = String(import.meta.env.VITE_SUPABASE_URL || "").replace(/\/+$/, "");
const FN_URL = `${SB_URL}/functions/v1/statements`;
const ANON = import.meta.env.VITE_SUPABASE_ANON_KEY as string;

export type StatementType = "expenses" | "earnings";
export type StatementPeriod =
  | { kind: "current" }
  | { kind: "month"; month: number; year: number }   // month 1-12
  | { kind: "year"; year: number };

export async function downloadStatementPdf(type: StatementType, period: StatementPeriod): Promise<{ error?: string }> {
  const { data: sess } = await supabase.auth.getSession();
  const token = sess.session?.access_token;
  if (!token) return { error: "Sign in to download statements." };

  try {
    const res = await fetch(FN_URL, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        apikey: ANON,
        authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({ type, period }),
    });
    if (!res.ok) {
      const msg = await res.json().catch(() => ({}));
      return { error: (msg as { error?: string }).error || `Download failed (${res.status})` };
    }
    const blob = await res.blob();
    // pull the filename the server suggested, else build one
    const cd = res.headers.get("content-disposition") || "";
    const m = cd.match(/filename="([^"]+)"/);
    const filename = m?.[1] || `${type}-statement.pdf`;

    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    a.remove();
    // revoke a tick later so the download has started
    setTimeout(() => URL.revokeObjectURL(url), 4000);
    return {};
  } catch (err) {
    return { error: (err as Error).message };
  }
}

// month name -> 1-12 (the pickers use full month names)
const MONTHS = ["January","February","March","April","May","June","July","August","September","October","November","December"];
export function monthNumber(name: string): number {
  const i = MONTHS.indexOf(name);
  return i >= 0 ? i + 1 : new Date().getMonth() + 1;
}
